### ISSUE TITLE
Simple GIt message Issue

### ISSUE THREAD

**Issue by SapneshNaik** [SapneshNaik/ae_test_1_oct#5]
Simple GIt message Issue

**Comment by angelleye-gitcommits** [comment]
Issue Status: 1. **Open** 2. Started 3. Submitted 4. Done

<hr>

**This issue now has a bounty of $50.00 attached to it.**

- If you would like to work on this issue you can 'start work' [on the GitCommits Issue Details page](https://sandbox.app.gitcommits.com/issue/simple-git-message-issue).
- Questions? Checkout [GitCommits Help](https://sandbox.gitcommits.com/help)
- More funded Bounties are available on the [GitCommits Issue Explorer](https://sandbox.app.gitcommits.com/explorer)

**Comment by angelleye-gitcommits** [comment]
**<a href='https://sandbox.app.gitcommits.com/profile/Test1-sap'>Test1-sap</a>, has started work on the bounty.**
<hr />

**Message:** started wewws


<a href='https://sandbox.app.gitcommits.com/issue/simple-git-message-issue'>Click Here to view more</a> on GitCommits Bounty detail page.

**Comment by angelleye-gitcommits** [comment]
**<a href='https://sandbox.app.gitcommits.com/profile/Test1-sap'>Test1-sap</a>, Your submission has been rejected by <a href='https://sandbox.app.gitcommits.com/profile/SapneshNaik'>SapneshNaik</a>.**
<hr />

**Message:** Pull Request has been rejected.


<a href='https://sandbox.app.gitcommits.com/issue/simple-git-message-issue'>Click Here to view more</a> on GitCommits Bounty detail page.

**Comment by angelleye-gitcommits** [comment]
### Warning:
Do not work on this Issue, Product Owner cancelled the Payment Method used to Pay the Bounties.
